name: dnsscanner

services:
  web:
    image: nginxinc/nginx-unprivileged:alpine-slim
    restart: always
    ports:
      - 80:8080
    volumes:
      - ./disclaimer:/usr/share/nginx/html:ro
      - ./log/nginx:/var/log/nginx
    configs:
      - source: nginx-server
        target: /etc/nginx/conf.d/default.conf
        uid: "101"
        gid: "101"
        mode: 0440
      - source: nginx
        target: /etc/nginx/nginx.conf
        uid: "101"
        gid: "101"
        mode: 0440

  db:
    image: postgres:alpine
    restart: always
    ports:
      - 127.0.0.1:5432:5432
    expose:
      - 5432
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./log/postgresql:/var/log/postgres
    configs:
      - source: postgresql
        target: /var/lib/postgressql/data/postgresql.conf
        mode: 0440
      - source: database
        target: /docker-entrypoint-initdb.d/init.sql
        mode: 0440
    secrets:
      - db_user
      - db_password
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
      - POSTGRES_USER_FILE=/run/secrets/db_user
      - POSTGRES_DB=dnsscanner
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      dnsscanner:
        ipv4_address: 192.168.53.54

  dns:
    image: coredns/coredns
    restart: always
    command: -conf /etc/coredns/Corefile -dns.port 53
    ports:
      - 127.0.0.1:5533:53/udp
    configs:
      - source: coredns
        target: /etc/coredns/Corefile
        mode: 0440
    expose:
      - 53
      - 53/udp
    networks:
      dnsscanner:
        ipv4_address: 192.168.53.53
    logging:
      driver: local

  nsec3map:
    restart: always
    build:
      context: /usr/src/nsec3map
      dockerfile: Dockerfile
    entrypoint: []
    command: sleep infinity
    secrets:
      - db_user
      - db_password
    dns:
      - 192.168.53.53
    networks:
      - dnsscanner
    depends_on:
      - db
      - dns
    scale: 10
#   Set the following limits according to your needs:
#   cpus: 0.6
#   mem_limit: 512M

networks:
  dnsscanner:
    ipam:
      driver: default
      config:
        - subnet: 192.168.53.0/24

configs:
  nginx-server:
    file: ./conf/nginx-server.conf
  nginx:
    file: ./conf/nginx.conf
  coredns:
    file: ./conf/Corefile
  postgresql:
    file: ./conf/postgresql.conf
  database:
    file: ./conf/init.sql

secrets:
  db_user:
    file: ./conf/db_user.txt
  db_password:
    file: ./conf/db_password.txt
